[package]
name = "kafka"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
envconfig.workspace = true
rdkafka.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true