[package]
name = "social-grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["full"] }
tonic.workspace = true
prost.workspace = true
social-store.workspace = true

[build-dependencies]
tonic-build.workspace = true